version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=banking_transactions_db;Username=soporte;Password=soporte
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: soporte
      POSTGRES_PASSWORD: soporte
      POSTGRES_DB: banking_transactions_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: